# Generated by Django 4.1.5 on 2023-01-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_report', '0002_disaster_report_location_alter_disaster_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster_report',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
