# Generated by Django 2.2.12 on 2023-01-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='forget_password',
        ),
    ]
