# Generated by Django 2.2.12 on 2023-01-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_remove_customuser_forget_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('volunteer_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('volunteer_address', models.CharField(max_length=100, null=True)),
                ('volunteer_skills', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='forget_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
