# Generated by Django 2.2.12 on 2023-01-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20230114_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('service_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('service_address', models.CharField(max_length=100, null=True)),
                ('service_type', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
