# Generated by Django 2.2.12 on 2023-01-14 22:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceadmin_name', models.CharField(max_length=100)),
                ('serviceadmin_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('serviceadmin_address', models.CharField(max_length=100)),
                ('serviceadmin_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
