# Generated by Django 4.1.5 on 2023-01-15 01:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_auto_20230114_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceadmin',
            name='serviceadmin_location',
        ),
        migrations.AddField(
            model_name='serviceadmin',
            name='serviceadmin_locations',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
